### ISSUE TITLE
Code not released

### ISSUE THREAD

**Issue by Grimwork** [dan11003/tbv_slam_public#2]
Hi,

In the [README.md](https://github.com/dan11003/tbv_slam_public/blob/master/README.md) in the section How to build with catkin
 you ask to clone these repositories :

> git clone -b master git@github.com:dan11003/tbv_slam_public.git
> git clone -b RAL-V1-SUBMISSION git@github.com:dan11003/tbv_slam.git
> git clone -b RAL-V1-SUBMISSION git@github.com:dan11003/CFEAR_Radarodometry_code_public.git
> git clone -b RAL-V1-SUBMISSION git@github.com:dan11003/CorAl-ScanAlignmentClassification.git branch 
> git clone -b RAL-V1-SUBMISSION git@github.com:dan11003/radar_kitti_benchmark.git
> git clone -b RAL-V1-SUBMISSION git@github.com:mattiask98/Place-Recognition-Radar-.git

But most of them like "git@github.com:dan11003/tbv_slam.git" are private so we don't have the permission to clone them.

**Comment by dan11003** [comment]
Hi Grimwork.
Thanks for posting an issue, I took the liberty to change the title.

The code of tbv slam is not yet released publicly, which is why you are unable to clone the private repos. I appologize that this is somewhat unclear at the moment, and that the readme is somewhat missleading.

I'm currently low on time but the plan is to provide a demo this fall.

**Comment by Grimwork** [comment]
Thanks for the quick answer.
Ok no problem, I'm looking forward to testing your code !
